export const caLoginobj = {
    "code": "200",
    "desc": "操作成功",
    "data": {
      "user": {
        "empNo": "admin",
        "empName": "管理员9",
        "createTime": null,
        "updateTime": "2022-07-04 13:58:20",
        "creatorNo": "",
        "auditedStatus": "waitAuditedDirector",
        "statusRead": "0",
        "detail": "dcdd",
        "attachmentId": "",
        "completeStatus": "handle",
        "statusColor": "0",
        "auditeListDtos": null,
        "auditedStatusName": "",
        "sign": false,
        "auditedEmpName": "",
        "auditedEmpRole": "",
        "id": 1,
        "sex": "1",
        "birthday": "1999-09-19",
        "deptCode": "041102",
        "deptName": "骨科护理单元",
        "title": "",
        "workYear": null,
        "education": "",
        "status": "在岗",
        "entryDate": null,
        "leaveDate": null,
        "superuser": true,
        "roles": "1",
        "groupId": null,
        "post": "护长",
        "icon": "2200404",
        "phone": "18933791430",
        "phoneStatus": true,
        "signature": "2200502",
        "age": "22",
        "publicAccount": "",
        "area": "",
        "inpatientArea": "",
        "specialAdmittance": "",
        "credit": "",
        "integral": "",
        "isNurse": true,
        "userType": "",
        "newTitle": "",
        "nurseHierarchy": "",
        "firstDegree": "",
        "rangeShow": false,
        "job": "护士长",
        "currentLevel": "",
        "nation": "蒙古族",
        "nativePlace": "湖南省衡阳市",
        "cardNumber": "450821199909190919",
        "cardZhUrl": "",
        "cardFanUrl": "",
        "address": "",
        "goWorkTime": "2022-05-26",
        "highestEducation": "博士",
        "zyzsNumber": "123jgfufutfkvhivuigyl卢珊",
        "zyzsUrl": "http://192.168.1.54:9885/crNursing/asset/nurseAttachment/20220531/202205311001023sKrZdaD.png,http://192.168.1.54:9885/crNursing/asset/nurseAttachment/20220609/20220609151423ncXY1J17.png",
        "specialCertificate": "",
        "specialCertificateNumber": "",
        "specialCertificateUrl": "",
        "socialGroup": "12",
        "technologyTitle": "",
        "nearImageUrl": "http://192.168.20.71:8080/crNursing/asset/nurseAttachment/20220610/20220610164453bNSrcKSg.png",
        "sortValue": null,
        "roleManage": "1",
        "roleManageCode": "QCR0001",
        "roleManageCodeList": [
          "QCR0001",
          "QCR0003",
          "QCR0004",
          "QCR0007",
          "SUPER_ADMIN",
          "SYS0001",
          "SY_RANGE"
        ],
        "roleCodeByJobList": [
          "ROLE_005",
          "ROLE_007"
        ],
        "saveStatus": "User",
        "newTitleNo": 3,
        "nurseHierarchyNo": 0,
        "jobNo": 6,
        "shortPhone": "",
        "deptPhone": "",
        "signSn": "",
        "signPic": "",
        "zyzsNursingPostDate": "2022-01-21",
        "zyzsDate": "2021-10-19",
        "jobStartDate": null,
        "locking": false,
        "loginError20Time": null,
        "noLoginRequired": false,
        "isNurseFile": "1",
        "maps": null,
        "xyzyjszg": "",
        "xyzyjszgjb": "",
        "xrzyjszw": "",
        "xrzyjszwjb": "",
        "nurse": true,
        "nursingStaff": true,
        "auditor": true
      },
      "authToken": "6da46357-67ec-4293-bc09-f608a3212481",
      "adminNurse": "管理员9"
    },
    "errorCode": ""
  }

