export const tableConfig = [
  [
    { name: 'A班', colspan: 9 },
    { name: 'P班', colspan: 9 },
    { name: 'N班', colspan: 9 },
  ],
  [
    { name: '类别', width: 60 },
    { name: '原有数' },
    { name: '入院数' },
    { name: '他科转入' },
    { name: '出院数' },
    { name: '转往他科' },
    { name: '死亡' },
    { name: '新生儿' },
    { name: '现有数' },
    { name: '类别', width: 60 },
    { name: '原有数' },
    { name: '入院数' },
    { name: '他科转入' },
    { name: '出院数' },
    { name: '转往他科' },
    { name: '死亡' },
    { name: '新生儿' },
    { name: '现有数' },
    { name: '类别', width: 60 },
    { name: '原有数' },
    { name: '入院数' },
    { name: '他科转入' },
    { name: '出院数' },
    { name: '转往他科' },
    { name: '死亡' },
    { name: '新生儿' },
    { name: '现有数' },
  ],
  [
    { name: '省本级' },
    { name: '', code: 'original1', type: 'A' },
    { name: '', code: 'inHospital1', type: 'A' },
    { name: '', code: 'transIn1', type: 'A' },
    { name: '', code: 'outHospital1', type: 'A' },
    { name: '', code: 'transOut1', type: 'A' },
    { name: '', code: 'death1', type: 'A' },
    { name: '', code: 'newborn1', type: 'A' },
    { name: '', code: 'patientNow1', type: 'A'},
    { name: '省本级' },
    { name: '', code: 'original1', type: 'P' },
    { name: '', code: 'inHospital1', type: 'P' },
    { name: '', code: 'transIn1', type: 'P' },
    { name: '', code: 'outHospital1', type: 'P' },
    { name: '', code: 'transOut1', type: 'P' },
    { name: '', code: 'death1', type: 'P' },
    { name: '', code: 'newborn1', type: 'P' },
    { name: '', code: 'patientNow1', type: 'P'},
    { name: '省本级' },
    { name: '', code: 'original1', type: 'N' },
    { name: '', code: 'inHospital1', type: 'N' },
    { name: '', code: 'transIn1', type: 'N' },
    { name: '', code: 'outHospital1', type: 'N' },
    { name: '', code: 'transOut1', type: 'N' },
    { name: '', code: 'death1', type: 'N' },
    { name: '', code: 'newborn1', type: 'N' },
    { name: '', code: 'patientNow1', type: 'N'},
  ],
  [
    { name: '省' },
    { name: '', code: 'original2', type: 'A' },
    { name: '', code: 'inHospital2', type: 'A' },
    { name: '', code: 'transIn2', type: 'A'  },
    { name: '', code: 'outHospital2', type: 'A'  },
    { name: '', code: 'transOut2', type: 'A'  },
    { name: '', code: 'death2', type: 'A'  },
    { name: '', code: 'newborn2', type: 'A'  },
    { name: '', code: 'patientNow2', type: 'A'  },
    { name: '省' },
    { name: '', code: 'original2', type: 'P' },
    { name: '', code: 'inHospital2', type: 'P' },
    { name: '', code: 'transIn2', type: 'P'  },
    { name: '', code: 'outHospital2', type: 'P'  },
    { name: '', code: 'transOut2', type: 'P'  },
    { name: '', code: 'death2', type: 'P'  },
    { name: '', code: 'newborn2', type: 'P'  },
    { name: '', code: 'patientNow2', type: 'P'  },
    { name: '省' },
    { name: '', code: 'original2', type: 'N' },
    { name: '', code: 'inHospital2', type: 'N' },
    { name: '', code: 'transIn2', type: 'N'  },
    { name: '', code: 'outHospital2', type: 'N'  },
    { name: '', code: 'transOut2', type: 'N'  },
    { name: '', code: 'death2', type: 'N'  },
    { name: '', code: 'newborn2', type: 'N'  },
    { name: '', code: 'patientNow2', type: 'N'  },
  ],
  [
    { name: '市' },
    { name: '', code: 'original3', type: 'A' },
    { name: '', code: 'inHospital3', type: 'A'  },
    { name: '', code: 'transIn3', type: 'A'  },
    { name: '', code: 'outHospital3', type: 'A'  },
    { name: '', code: 'transOut3', type: 'A'  },
    { name: '', code: 'death3', type: 'A'  },
    { name: '', code: 'newborn3', type: 'A'  },
    { name: '', code: 'patientNow3', type: 'A'  },
    { name: '市' },
    { name: '', code: 'original3', type: 'P' },
    { name: '', code: 'inHospital3', type: 'P'  },
    { name: '', code: 'transIn3', type: 'P'  },
    { name: '', code: 'outHospital3', type: 'P'  },
    { name: '', code: 'transOut3', type: 'P'  },
    { name: '', code: 'death3', type: 'P'  },
    { name: '', code: 'newborn3', type: 'P'  },
    { name: '', code: 'patientNow3', type: 'P'  },
    { name: '市' },
    { name: '', code: 'original3', type: 'N' },
    { name: '', code: 'inHospital3', type: 'N'  },
    { name: '', code: 'transIn3', type: 'N'  },
    { name: '', code: 'outHospital3', type: 'N'  },
    { name: '', code: 'transOut3', type: 'N'  },
    { name: '', code: 'death3', type: 'N'  },
    { name: '', code: 'newborn3', type: 'N'  },
    { name: '', code: 'patientNow3', type: 'N'  },
  ],
  [
    { name: '其他' },
    { name: '', code: 'original4', type: 'A' },
    { name: '', code: 'inHospital4', type: 'A' },
    { name: '', code: 'transIn4', type: 'A' },
    { name: '', code: 'outHospital4', type: 'A' },
    { name: '', code: 'transOut4', type: 'A' },
    { name: '', code: 'death4', type: 'A' },
    { name: '', code: 'newborn4', type: 'A' },
    { name: '', code: 'patientNow4', type: 'A' },
    { name: '其他' },
    { name: '', code: 'original4', type: 'P' },
    { name: '', code: 'inHospital4', type: 'P' },
    { name: '', code: 'transIn4', type: 'P' },
    { name: '', code: 'outHospital4', type: 'P' },
    { name: '', code: 'transOut4', type: 'P' },
    { name: '', code: 'death4', type: 'P' },
    { name: '', code: 'newborn4', type: 'P' },
    { name: '', code: 'patientNow4', type: 'P' },
    { name: '其他' },
    { name: '', code: 'original4', type: 'N' },
    { name: '', code: 'inHospital4', type: 'N' },
    { name: '', code: 'transIn4', type: 'N' },
    { name: '', code: 'outHospital4', type: 'N' },
    { name: '', code: 'transOut4', type: 'N' },
    { name: '', code: 'death4', type: 'N' },
    { name: '', code: 'newborn4', type: 'N' },
    { name: '', code: 'patientNow4', type: 'N' },
  ],
  [
    { name: '总计' },
    { name: '', code: 'original5', type: 'A' },
    { name: '', code: 'inHospital5', type: 'A' },
    { name: '', code: 'transIn5', type: 'A' },
    { name: '', code: 'outHospital5', type: 'A' },
    { name: '', code: 'transOut5', type: 'A' },
    { name: '', code: 'death5', type: 'A' },
    { name: '', code: 'newborn5', type: 'A'},
    { name: '', code: 'patientNow5', type: 'A' },
    { name: '总计' },
     { name: '', code: 'original5', type: 'P' },
    { name: '', code: 'inHospital5', type: 'P' },
    { name: '', code: 'transIn5', type: 'P' },
    { name: '', code: 'outHospital5', type: 'P' },
    { name: '', code: 'transOut5', type: 'P' },
    { name: '', code: 'death5', type: 'P' },
    { name: '', code: 'newborn5', type: 'P'},
    { name: '', code: 'patientNow5', type: 'P' },
    { name: '总计' },
     { name: '', code: 'original5', type: 'N' },
    { name: '', code: 'inHospital5', type: 'N' },
    { name: '', code: 'transIn5', type: 'N' },
    { name: '', code: 'outHospital5', type: 'N' },
    { name: '', code: 'transOut5', type: 'N' },
    { name: '', code: 'death5', type: 'N' },
    { name: '', code: 'newborn5', type: 'N'},
    { name: '', code: 'patientNow5', type: 'N' },
  ],
  [
    { name: '应注意事项', colspan: 9 },
    { name: '应注意事项', colspan: 9 },
    { name: '应注意事项', colspan: 9 },
  ]
]

export const bodyColumns = [
    {
      label: "床号",
      prop: "bedLabel",
      editable: false,
      align: "center",
      width: "50px"
    },
    {
      label: "姓名",
      prop: "name",
      width: "80px",
      editable: false,
      align: "center",
    },
    {
      label: "诊断",
      prop: "diagnosis",
      editable: false,
      width: "150px"
    },
    {
      label: "A",
      prop: "notea",
      editable: false,
      width: "253px"
    },
    {
      label: "P",
      prop: "notep",
      editable: false,
      width: "253px"
    },
    {
      label: "N",
      prop: "noten",
      editable: false,
      width: "253px"
    }
]
    
    