export const tableColumns = [
  {
    key: 'consultationTime',
    title: '申请时间',
    align: 'center',
    width: 180,
  },
  {
    key: 'createTime',
    title: '会诊时间',
    align: 'center',
    width: 180,
  },
  {
    key: 'deptName',
    title: '申请科室',
    align: 'center',
    width: 200,
  },
  {
    key: 'creator',
    title: '申请人',
    align: 'center',
    width: 100,
  },
  {
    key: 'consultationObject',
    title: '会诊对象',
    align: 'center',
    width: 100,
  },
  {
    key: 'nursingDiagnosis',
    title: '诊断',
    align: 'center',
    width: 200,
  },
  {
    key: 'consultationPurposes',
    title: '主诉',
    align: 'center',
    width: 240,
  },
  {
    key: 'consultationHistory',
    title: '简要病史',
    align: 'center',
    width: 220,
  },
  {
    key: 'mainNursingMessage',
    title: '主要护理问题',
    align: 'center',
    width: 180,
  },
  {
    key: 'consultationDeptName',
    title: '受邀科室',
    align: 'center',
    width: 150,
  },
  {
    key: 'empName',
    title: '受邀护士',
    align: 'center',
    width: 100,
  },
  {
    key: 'content',
    title: '护理会诊情况及意见',
    align: 'center',
    width: 250,
  },
]


export const mockData = {
  "list": [
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:37:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "张三",
          "nursingDiagnosis": "共同讨论得出护理诊断。",
          "consultationPurposes": "目的是什么？",
          "consultationHistory": "目的是什么？",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*珍",
          "content": "星辰不可及"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:37:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "张三",
          "nursingDiagnosis": "共同讨论得出护理诊断。",
          "consultationPurposes": "目的是什么？",
          "consultationHistory": "目的是什么？",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*玲",
          "content": "星辰不可及"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-28 17:55:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "bbbb",
          "nursingDiagnosis": "ddddd1121938127930131-0j1to\nwou92ur39r-2ir3-ri910ri3ri21rr90ir-\ni30t043ut02tu4t92tut2tuu49tu94t4utu9t3u90ut0tu09t9tu03tu0tu09t3",
          "consultationPurposes": "ccccccccc",
          "consultationHistory": "ccccccccc",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*祺",
          "content": "共产党人拥有人格力量，才能赢得民心。全党同志都要明大德、守公德、严私德，清清白白做人、干干净净做事，做到克己奉公、以俭修身，永葆清正廉洁的政治本色777"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:37:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "张三",
          "nursingDiagnosis": "共同讨论得出护理诊断。",
          "consultationPurposes": "目的是什么？",
          "consultationHistory": "目的是什么？",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "朱娜娜",
          "content": "星辰不可及"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-28 17:55:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "bbbb",
          "nursingDiagnosis": "ddddd1121938127930131-0j1to\nwou92ur39r-2ir3-ri910ri3ri21rr90ir-\ni30t043ut02tu4t92tut2tuu49tu94t4utu9t3u90ut0tu09t9tu03tu0tu09t3",
          "consultationPurposes": "ccccccccc",
          "consultationHistory": "ccccccccc",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*月",
          "content": "共产党人拥有人格力量，才能赢得民心。全党同志都要明大德、守公德、严私德，清清白白做人、干干净净做事，做到克己奉公、以俭修身，永葆清正廉洁的政治本色777"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-28 17:55:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "bbbb",
          "nursingDiagnosis": "ddddd1121938127930131-0j1to\nwou92ur39r-2ir3-ri910ri3ri21rr90ir-\ni30t043ut02tu4t92tut2tuu49tu94t4utu9t3u90ut0tu09t9tu03tu0tu09t3",
          "consultationPurposes": "ccccccccc",
          "consultationHistory": "ccccccccc",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*兴",
          "content": "共产党人拥有人格力量，才能赢得民心。全党同志都要明大德、守公德、严私德，清清白白做人、干干净净做事，做到克己奉公、以俭修身，永葆清正廉洁的政治本色777"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-28 17:55:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "bbbb",
          "nursingDiagnosis": "ddddd1121938127930131-0j1to\nwou92ur39r-2ir3-ri910ri3ri21rr90ir-\ni30t043ut02tu4t92tut2tuu49tu94t4utu9t3u90ut0tu09t9tu03tu0tu09t3",
          "consultationPurposes": "ccccccccc",
          "consultationHistory": "ccccccccc",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*珊",
          "content": "共产党人拥有人格力量，才能赢得民心。全党同志都要明大德、守公德、严私德，清清白白做人、干干净净做事，做到克己奉公、以俭修身，永葆清正廉洁的政治本色777"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-28 17:55:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "bbbb",
          "nursingDiagnosis": "ddddd1121938127930131-0j1to\nwou92ur39r-2ir3-ri910ri3ri21rr90ir-\ni30t043ut02tu4t92tut2tuu49tu94t4utu9t3u90ut0tu09t9tu03tu0tu09t3",
          "consultationPurposes": "ccccccccc",
          "consultationHistory": "ccccccccc",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*君",
          "content": "共产党人拥有人格力量，才能赢得民心。全党同志都要明大德、守公德、严私德，清清白白做人、干干净净做事，做到克己奉公、以俭修身，永葆清正廉洁的政治本色777"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-28 17:55:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "bbbb",
          "nursingDiagnosis": "ddddd1121938127930131-0j1to\nwou92ur39r-2ir3-ri910ri3ri21rr90ir-\ni30t043ut02tu4t92tut2tuu49tu94t4utu9t3u90ut0tu09t9tu03tu0tu09t3",
          "consultationPurposes": "ccccccccc",
          "consultationHistory": "ccccccccc",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*花 ",
          "content": "共产党人拥有人格力量，才能赢得民心。全党同志都要明大德、守公德、严私德，清清白白做人、干干净净做事，做到克己奉公、以俭修身，永葆清正廉洁的政治本色777"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:37:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "张三",
          "nursingDiagnosis": "共同讨论得出护理诊断。",
          "consultationPurposes": "目的是什么？",
          "consultationHistory": "目的是什么？",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*媛",
          "content": "星辰不可及"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-08-25 18:25:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员8",
          "consultationObject": "",
          "nursingDiagnosis": "",
          "consultationPurposes": "",
          "consultationHistory": "",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员8",
          "content": ""
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-09-25 18:25:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员8",
          "consultationObject": "",
          "nursingDiagnosis": "",
          "consultationPurposes": "",
          "consultationHistory": "",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员8",
          "content": ""
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-02-25 18:25:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员8",
          "consultationObject": "",
          "nursingDiagnosis": "",
          "consultationPurposes": "",
          "consultationHistory": "",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员8",
          "content": ""
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-02-25 18:25:00",
          "deptName": "",
          "creator": "问问",
          "consultationObject": "",
          "nursingDiagnosis": "",
          "consultationPurposes": "",
          "consultationHistory": "",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员8",
          "content": ""
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-07-20 11:11:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员9",
          "consultationObject": "彭*萍",
          "nursingDiagnosis": "",
          "consultationPurposes": "dsds",
          "consultationHistory": "dsds",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员9",
          "content": ""
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-07-20 11:12:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员9",
          "consultationObject": "彭*萍",
          "nursingDiagnosis": "",
          "consultationPurposes": "12",
          "consultationHistory": "12",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员9",
          "content": ""
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-11-09 10:55:17",
          "deptName": "心血管介入护理单元",
          "creator": "管理员9",
          "consultationObject": "田*伟",
          "nursingDiagnosis": "诊断",
          "consultationPurposes": "目的",
          "consultationHistory": "目的",
          "mainNursingMessage": "问题",
          "consultationDeptName": "骨一科护理单元",
          "empName": "张三",
          "content": "啦啦啦啦啦啦啦啦\n"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-11-09 10:55:17",
          "deptName": "心血管介入护理单元",
          "creator": "管理员9",
          "consultationObject": "田*伟",
          "nursingDiagnosis": "诊断",
          "consultationPurposes": "目的",
          "consultationHistory": "目的",
          "mainNursingMessage": "问题",
          "consultationDeptName": "骨一科护理单元",
          "empName": "孙琳",
          "content": "啦啦啦啦啦啦啦啦\n"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-11-09 10:55:17",
          "deptName": "心血管介入护理单元",
          "creator": "管理员9",
          "consultationObject": "田*伟",
          "nursingDiagnosis": "诊断",
          "consultationPurposes": "目的",
          "consultationHistory": "目的",
          "mainNursingMessage": "问题",
          "consultationDeptName": "骨一科护理单元",
          "empName": "黄辉冯",
          "content": "啦啦啦啦啦啦啦啦\n"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*媛",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*珍",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陈*玲",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "管理员",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "高*",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "黄*冰",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "陆*",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "梁*娣",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "aaa",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "梁*桐",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "李*燕",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "李*萍",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "黎*珺",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "威军",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "温*琴",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "韦*",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "王*媛",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "朱娜娜",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "朱*琴",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "周*芳",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2021-06-29 17:26:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员",
          "consultationObject": "王大锤",
          "nursingDiagnosis": "诊断为空明明哦咯咯了哦",
          "consultationPurposes": "没有目的目的",
          "consultationHistory": "没有目的目的",
          "mainNursingMessage": "",
          "consultationDeptName": "",
          "empName": "赵*",
          "content": "我是用手机红色偷偷里哦评论头送心哦送送我在群里给我"
      },
      {
          "wardCode": "",
          "wardName": "",
          "consultationTime": "2022-12-20 11:44:00",
          "deptName": "心血管介入护理单元",
          "creator": "管理员9",
          "consultationObject": "李*",
          "nursingDiagnosis": "1",
          "consultationPurposes": "",
          "consultationHistory": "",
          "mainNursingMessage": "",
          "consultationDeptName": "骨一科护理单元",
          "empName": "",
          "content": "1"
      }
  ],
  "page": 1,
  "totalCount": 0
}
